# Generated by Django 2.2.5 on 2019-11-12 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('short_link', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='short_url',
        ),
    ]
