# Generated by Django 2.2.5 on 2019-11-12 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('short_link', '0002_remove_link_short_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='_short_url',
            field=models.URLField(db_column='short_url', default='http://os.pl'),
            preserve_default=False,
        ),
    ]
