# Generated by Django 2.2.5 on 2019-11-12 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('short_link', '0003_link__short_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_my_date', models.DateField(db_column='my_date')),
            ],
        ),
    ]
