# Generated by Django 2.2.5 on 2019-11-12 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('short_link', '0004_myclass'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyClass',
        ),
    ]
