# Generated by Django 2.2.5 on 2019-11-13 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('short_link', '0005_delete_myclass'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='_short_url',
        ),
        migrations.AddField(
            model_name='link',
            name='short_url',
            field=models.URLField(default='http://short.me/<django.db.models.fields.AutoField>'),
        ),
        migrations.AlterField(
            model_name='link',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
